<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sign_In</name>
   <tag></tag>
   <elementGuidId>a33a3a11-cdc3-4b91-bf27-9fffc657d1d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.sign-in</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
